[package]
name = "ssh-principals"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "basic-ssh-principals"
path = "src/basic/bin/main.rs"

[[bin]]
name = "time-based-ssh-principals"
path = "src/time-based/bin/main.rs"
